# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(726, 645)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(190, 50, 281, 61))
        self.label.setStyleSheet("color :rgb(255, 0, 0);\n"
"font : 75 17pt \"MS Sans Serif\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 210, 211, 31))
        self.label_2.setStyleSheet("color:rgb(85, 0, 255);\n"
"font: 75 14pt \"Georgia\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 270, 191, 41))
        self.label_3.setStyleSheet("color:rgb(85, 0, 255);\n"
"font: 75 14pt \"Georgia\";")
        self.label_3.setObjectName("label_3")
        self.first_name = QtWidgets.QLineEdit(Form)
        self.first_name.setGeometry(QtCore.QRect(280, 200, 211, 41))
        self.first_name.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 22pt \"Microsoft Himalaya\";")
        self.first_name.setObjectName("first_name")
        self.last_name = QtWidgets.QLineEdit(Form)
        self.last_name.setGeometry(QtCore.QRect(280, 270, 211, 41))
        self.last_name.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 22pt \"Microsoft Himalaya\";")
        self.last_name.setObjectName("last_name")
        self.generate_button = QtWidgets.QPushButton(Form)
        self.generate_button.setGeometry(QtCore.QRect(310, 360, 131, 51))
        self.generate_button.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 22pt \"Microsoft Himalaya\";")
        self.generate_button.setObjectName("generate_button")
        self.full_name = QtWidgets.QLabel(Form)
        self.full_name.setGeometry(QtCore.QRect(80, 450, 141, 41))
        self.full_name.setStyleSheet("color:rgb(85, 0, 255);\n"
"font: 75 14pt \"Georgia\";")
        self.full_name.setObjectName("full_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "            Adding Name"))
        self.label_2.setText(_translate("Form", "Enter First Name : "))
        self.label_3.setText(_translate("Form", "Enter Last Name:"))
        self.generate_button.setText(_translate("Form", "Generate"))
        self.full_name.setText(_translate("Form", "Full Name: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
